// <auto-generated />
using System;
using Api.Common.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241124214311_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ParkingSpots.ParkingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParkingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.HasIndex("UserIdentity")
                        .IsUnique();

                    b.HasIndex("UserIdentity", "SpotName")
                        .IsUnique();

                    b.ToTable("ParkingLot");
                });

            modelBuilder.Entity("Domain.Parkings.Parking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Parking");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<string>("Identity")
                        .HasColumnType("text");

                    b.HasKey("Identity");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Credits")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PendingCredits")
                        .HasColumnType("numeric");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentity")
                        .IsUnique();

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("Domain.ParkingSpots.ParkingLot", b =>
                {
                    b.HasOne("Domain.Parkings.Parking", null)
                        .WithMany()
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.ParkingSpots.ParkingLot", "UserIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.ParkingSpots.ParkingSpotAvailability", "Availabilities", b1 =>
                        {
                            b1.Property<Guid>("ParkingLotId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ParkingLotId", "Id");

                            b1.ToTable("ParkingSpotAvailability");

                            b1.WithOwner()
                                .HasForeignKey("ParkingLotId");
                        });

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("Domain.Wallets.Wallet", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Wallets.Wallet", "UserIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
