@Api_HostAddress = http://localhost:5014

POST {{Api_HostAddress}}/@me/register
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

POST {{Api_HostAddress}}/@me/register
Accept: application/json
Authorization: Bearer {{$auth.token("other")}}

###

GET {{Api_HostAddress}}/parking?search=
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

GET {{Api_HostAddress}}/@me/spot
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

PUT {{Api_HostAddress}}/@me/spot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("me")}}

{
  "parkingId": "41fbf549-1ee9-4445-b138-5efc97079cad",
  "lotName": "abc"
}

###

PUT {{Api_HostAddress}}/@me/spot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("other")}}

{
  "parkingId": "41fbf549-1ee9-4445-b138-5efc97079cad",
  "lotName": "FGH"
}

###

GET {{Api_HostAddress}}/@me/status
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

GET {{Api_HostAddress}}/@me/status
Accept: application/json
Authorization: Bearer {{$auth.token("other")}}

###

POST {{Api_HostAddress}}/@me/spot/availability
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("me")}}

{
  "from": "2024-12-02T07:06:00+01:00",
  "to": "2024-12-02T11:20:00+01:00"
}

###

POST {{Api_HostAddress}}/@me/spot/availability
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("other")}}

{
  "from": "2024-11-29T01:17:00+01:00",
  "to": "2024-11-29T19:00:00+01:00"
}

###

GET {{Api_HostAddress}}/@me/spot/availabilities
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

GET {{Api_HostAddress}}/spots?from=2024-11-29T01:20:00&minDuration=02:00:00
Accept: application/json
Authorization: Bearer {{$auth.token("me")}}

###

POST {{Api_HostAddress}}/spots/booking
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("me")}}

{
  "parkingLotId": "01937546-63e8-7a16-a8b1-f59e86555d9c",
  "from": "2024-11-29T01:21:00+00:00",
  "duration": "02:46:13"
}
