@Api_HostAddress = http://localhost:5014

GET {{Api_HostAddress}}/parking/
Accept: application/json

###

GET {{Api_HostAddress}}/@me/spot
Accept: application/json

###

POST {{Api_HostAddress}}/@me/spot
Accept: application/json
Content-Type: application/json

{
  "parkingId": "b0c97c6b-028d-4c85-b713-826fa2aa0851",
  "lotName": "36bazF"
}
