version: '3.8'
name: friendspot

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: friendspot@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES__CONNECTION_STRING: Host=postgres;Database=app;Username=postgres;Password=postgres
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - app-network

volumes:
  postgres_data:
  pgadmin-data:


networks:
  app-network:
