version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES__CONNECTION_STRING: Host=postgres;Database=app;Username=postgres;Password=postgres
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
