export function Privacy() {
  return (
    <div className="privacy-container max-w-4xl mx-auto p-6 space-y-6">
      <h1 className="text-3xl font-bold">Privacy Policy</h1>
      <p>Last updated: August 27, 2025</p>

      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{" "}
        <a
          href="https://www.termsfeed.com/privacy-policy-generator/"
          target="_blank"
          className="text-blue-600 underline"
        >
          Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold mt-6">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold mt-4">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li>
          <strong>Application</strong> refers to FriendSpot, the software
          program provided by the Company.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to FriendSpot.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: France
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Application or the Website or
          both.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to FriendSpot, accessible from{" "}
          <a
            href="https://friendspot.app/"
            className="text-blue-600 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://friendspot.app/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold mt-3">Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc list-inside space-y-2">
        <li>Email address</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold mt-3">Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>

      <h4 className="text-lg font-semibold mt-3">
        Information Collected while Using the Application
      </h4>
      <p>
        While using Our Application, in order to provide features of Our
        Application, We may collect, with Your prior permission:
      </p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          Pictures and other information from your Device's camera and photo
          library
        </li>
      </ul>
      <p>
        We use this information to provide features of Our Service, to improve
        and customize Our Service. The information may be uploaded to the
        Company's servers and/or a Service Provider's server or it may be simply
        stored on Your device.
      </p>
      <p>
        You can enable or disable access to this information at any time,
        through Your Device settings.
      </p>

      <h4 className="text-lg font-semibold mt-3">
        Tracking Technologies and Cookies
      </h4>
      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>

      <p>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web browser.
        You can learn more about cookies on{" "}
        <a
          href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
          className="text-blue-600 underline"
          target="_blank"
        >
          TermsFeed website
        </a>{" "}
        article.
      </p>

      <p>
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          <strong>Necessary / Essential Cookies</strong> - Type: Session Cookies
          - Administered by: Us - Purpose: These Cookies are essential to
          provide You with services available through the Website and to enable
          You to use some of its features. They help to authenticate users and
          prevent fraudulent use of user accounts.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong> - Type:
          Persistent Cookies - Administered by: Us - Purpose: These Cookies
          identify if users have accepted the use of cookies on the Website.
        </li>
        <li>
          <strong>Functionality Cookies</strong> - Type: Persistent Cookies -
          Administered by: Us - Purpose: These Cookies allow us to remember
          choices You make when You use the Website, such as remembering your
          login details or language preference.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mt-4">Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside space-y-2">
        <li>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration
          as a user of the Service.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development,
          compliance and undertaking of the purchase contract for the products,
          items or services You have purchased.
        </li>
        <li>
          <strong>To contact You:</strong> via email, phone, SMS, or push
          notifications for updates and communications.
        </li>
        <li>
          <strong>To provide You</strong> with news, offers, and information on
          similar products/services.
        </li>
        <li>
          <strong>To manage Your requests:</strong> To attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> mergers, sales, acquisitions,
          etc.
        </li>
        <li>
          <strong>For other purposes</strong>: data analysis, improving
          services, marketing, etc.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mt-4">
        Disclosure of Your Personal Data
      </h3>
      <ul className="list-disc list-inside space-y-2">
        <li>
          <strong>With Service Providers:</strong> monitor and analyze use of
          Service, contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> share during mergers,
          acquisitions, sales.
        </li>
        <li>
          <strong>With Affiliates:</strong> affiliates honor Privacy Policy.
        </li>
        <li>
          <strong>With business partners:</strong> offer products, services or
          promotions.
        </li>
        <li>
          <strong>With other users:</strong> public interactions.
        </li>
        <li>
          <strong>With Your consent:</strong> any other purpose with consent.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mt-4">
        Retention of Your Personal Data
      </h3>
      <p>
        The Company retains Personal Data only as long as necessary and Usage
        Data for internal analysis, unless legally required otherwise.
      </p>

      <h3 className="text-xl font-semibold mt-4">
        Transfer of Your Personal Data
      </h3>
      <p>
        Data may be processed and stored outside your jurisdiction. Consent to
        this Privacy Policy implies agreement to the transfer. Security measures
        are applied to protect Your data.
      </p>

      <h3 className="text-xl font-semibold mt-4">Delete Your Personal Data</h3>
      <p>
        You can delete or request deletion of Personal Data by contacting the
        Company or via account settings. Certain data may need to be retained
        for legal obligations.
      </p>

      <h3 className="text-xl font-semibold mt-4">
        Security of Your Personal Data
      </h3>
      <p>
        We use commercially acceptable measures to protect Your data but cannot
        guarantee absolute security over the Internet.
      </p>

      <h2 className="text-2xl font-semibold mt-6">Children's Privacy</h2>
      <p>
        The Service is not intended for children under 13. If We collect data
        from a child under 13, we take steps to remove it.
      </p>

      <h2 className="text-2xl font-semibold mt-6">Links to Other Websites</h2>
      <p>
        The Service may contain links to third-party websites. We are not
        responsible for their content or privacy practices.
      </p>

      <h2 className="text-2xl font-semibold mt-6">
        Changes to this Privacy Policy
      </h2>
      <p>
        We may update this Privacy Policy from time to time. Changes will be
        posted on this page with the new "Last updated" date.
      </p>

      <h2 className="text-2xl font-semibold mt-6">Contact Us</h2>
      <ul className="list-disc list-inside space-y-2">
        <li>
          By email:{" "}
          <a
            href="mailto:support@friendspot.app"
            className="text-blue-600 underline"
          >
            support@friendspot.app
          </a>
        </li>
      </ul>
    </div>
  );
}

export default Privacy;
