# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: cd backend
      run: cd ./backend
    - name: Restore dependencies
      run: dotnet restore backend.sln
    - name: Build
      run: dotnet build backend.sln --no-restore
    - name: Domain tests
      run: dotnet test Domain.Tests --no-build --verbosity normal
    - name: API tests
      run: dotnet test Api.Tests --no-build --verbosity normal
